--TO CREATE A DATABASE
CREATE DATABASE EMPLOYEE_DATABASE;

USE EMPLOYEE_DATABASE;

--TO CREATE A DEPARTMENT TABLE
CREATE TABLE DEPARTMENT(
DEPARTMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
DEPARTMENT_NAME VARCHAR (30)
);

--TO CREATE A LOCATION TABLE 
CREATE TABLE LOCATION(
LOCATION_ID INT PRIMARY KEY,
LOCATION_NAME VARCHAR (20)
);

-- TO CREATE A EMPLOYEES TABLE 
CREATE TABLE EMPLOYEES(
EMPLOYEE_ID INT PRIMARY KEY,
EMPLOYEE_NAME VARCHAR(30),
GENDER VARCHAR(5),
AGE INT, 
HIRE_DATE DATE, 
DESIGNATION VARCHAR(20),
SALARY INT,
DEPARTMENT_ID INT,
LOCATION_ID INT,
    
FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID),
FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(LOCATION_ID)
);

--TO ALTER TABLE
ALTER TABLE EMPLOYEES
ADD EMAIL VARCHAR(50);

--TO ALTER TABLE
ALTER TABLE EMPLOYEES
MODIFY DESIGNATION VARCHAR(50);

--TO ALTER EMPLOYEES TABLE 
ALTER TABLE EMPLOYEES
DROP COLUMN AGE;

--TO ALTER EMPLOYEES TABLE
ALTER TABLE EMPLOYEES
RENAME COLUMN HIRE_DATE TO DATE_OF_JOINING;

--TO RENAME TABLE NAME
RENAME TABLE Department TO Departments_Info;

--TO RENAME TABLE NAME 
RENAME TABLE Location TO Locations;

--TO TRUNCATE TABLE
TRUNCATE TABLE EMPLOYEES;

--TO DROP TABLE
DROP TABLE EMPLOYEES;

--TO DROP DATABASE
DROP DATABASE employee;

DROP DATABASE IF EXISTS employee;

--TO CREATE A DATABASE
CREATE DATABASE employee;

USE employee;

--TO CREATE A TABLE
CREATE TABLE DEPARTMENTS (
DEPARTMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
DEPARTMENT_NAME VARCHAR(50) NOT NULL UNIQUE
);


--TO CREATE A TABLE 
CREATE TABLE LOCATIONS (
LOCATION_ID INT AUTO_INCREMENT PRIMARY KEY,
LOCATION_NAME VARCHAR(50) NOT NULL UNIQUE
);

--TO CREATE A TABLE
CREATE TABLE EMPLOYEES (
EMPLOYEE_ID INT AUTO_INCREMENT PRIMARY KEY,
EMPLOYEE_NAME VARCHAR(50) NOT NULL,
GENDER CHAR(1),
AGE INT,
HIRE_DATE DATE DEFAULT(CURRENT_DATE),
DESIGNATION VARCHAR(50),
SALARY INT,
DEPARTMENT_ID INT,
LOCATION_ID INT,
CHECK (GENDER IN ('M','F')),
CHECK (AGE >= 18),
FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID),
FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID)
);




